import "dotenv/config";
import express from "express";
import cors from "cors";
import userRoutes from "./routes/user.routes.js";
import authRoutes from "./routes/auth.routes.js";
const app=express();
const PORT=process.env.PORT||5000;
app.use(cors({origin:process.env.CORS_ORIGIN||"http://localhost:5173"}));
app.use(express.json());
app.get("/api/health",(req,res)=>res.json({success:true,message:"API is running"}));
app.use("/api/auth",authRoutes);
app.use("/api/users",userRoutes);
app.use((req,res)=>res.status(404).json({message:"Route not found."}));
app.listen(PORT,"0.0.0.0",()=>console.log(`API running on http://localhost:${PORT}`));
